### ISSUE TITLE
Searching for a type of profile seems to return all resources of that type, not profiles

### ISSUE THREAD

**Issue by ewoutkramer** [furore-fhir/spark#15]
http://spark.furore.com/fhir/Profile?type=Observation seems to return observations, not profiles about Observation. Is that a bug?

**Comment by CorinaCiocanea** [comment]
This is the same issue with #54. I already have a possible solution for that one, but "a more in depth" discussion might be needed.

**Comment by CorinaCiocanea** [comment]
These issue contained multiple problems:
- the first one is the fact the the "type" parameter was wrongly treated (fixed by #36)
- the second one, a problem with search parameter of type Token that correspond to string or bool properties on the actual resource.
The url in the initial comment is no longer valid. Currently this issue can be tested with a url like fhir/StructureDefinition?type=Quantity
