### ISSUE TITLE
Bundle when retrieved in XML format is wrapped in CData encoding.

### ISSUE THREAD

**Issue by revathysreenath** [furore-fhir/spark#42]
Hi,

In DSTU2 when we GET search results for a resource in XML format , the response is not XML instead its wrapped in CDATA encoding. This needs to be taken care by XML parser to represent this data as XML upon retrieval. When we use tools like Fiddler or postman , this is automatically taken care by parser however when using Soap UI all my scripts which written for DSTU1 using XPath for Data validations fail. 

This is observed only in case of Spark(DSTU2 code base and Test server) however when testing using Grahame's test server http://fhir-dev.healthintersections.com.au this is not observed

Thanks,
Revathy

**Comment by revathysreenath** [comment]
For this in XMLFHIRFormatter [sparkengine/formatters/] I turned off the UTF8 enconding on the XML writer. This works fine from all tools now Fiddler/Postman/SoapUI. Is there any impact change I need to look into for the same?

**Comment by CorinaCiocanea** [comment]
The CData encoding was specifically added by the Soap UI application because it didn't know how else to handle the BOM (https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8 ) received in the response. The actual problem was that the .net UTF8 enconded response also contained a byte order mark prefix, that was correctly interpreted/ignored by most tools, but not by all. I've removed that.
