### ISSUE TITLE
Searching for list of codes in Observation

### ISSUE THREAD

**Issue by jokkis0** [furore-fhir/spark#62]
Hi, 
I have a question regarding searching for Observations by list of codes. 
I have tried several alternatives, but only one single code in url works. 

http://spark-dstu2.furore.com/fhir/Observation?patient.identifier=12345&code=30350-3$150456
http://spark-dstu2.furore.com/fhir/Observation?patient.identifier=12345&code=30350-3|150456
http://spark-dstu2.furore.com/fhir/Observation?patient.identifier=12345&code=30350-3,150456

**Comment by mbaltus** [comment]
Hi Joachim,

the third syntax should be the correct one, where you list the codes with a comma to make an 'or' search. I've tried it succesfully with:
http://spark.furore.com/fhir/Observation?patient.identifier=12345&code=55284-4,9269-2

We've had several bugs in our search due to some refactoring during November. This one seems to have been fixed. Could you verify that it works for you as well?
