### ISSUE TITLE
Allow a command for reset - initialize of the database

### ISSUE THREAD

**Issue by mharthoorn** [furore-fhir/spark#83]
We made the the database reset interactive using SignalR. But that way a reset can't be scheduled, using a tools like curl or wget.

Proposal to add a url-runnable command.

**Comment by mohannadhussain** [comment]
I have found a work around, the following commands can be put into a .bat (Windows Batch) file and schedule as a task if necessary:

```
setlocal
start iexplore.exe localhost/maintenance/initialize
timeout /t 120
taskkill /IM iexplore.exe /FI "WINDOWTITLE eq Spark*
```

**Comment by CorinaCiocanea** [comment]
We've added a REST endpoint to delete all data in the database.
Curl usage example:
```curl -X DELETE  http://localhost:49911/MaintenanceApi/ClearAll```

**Comment by CorinaCiocanea** [comment]
A small update on this one. In order to only allow this operation for server owners, I've changed the api to require an access code that can be set in web.config in the following way:

 ```<appSettings>
    <add key="clearAllCode" value="4cf56b8b-cc6a-4bbf-ab65-aa4518c4897e"/>
...
 </appSettings>```

Afterwards , to access this operation one will need to call it like
```curl -X DELETE http://localhost:49911/MaintenanceApi/All?access=4cf56b8b-cc6a-4bbf-ab65-aa4518c4897e```

One can also remove the setting altogether from web.config and that will disable the clear all operation. I strongly suggest removing this in production, since it's not an appropriate security measure for production servers.
